### ISSUE TITLE
A "Made in Kunnamkulam" sticker

### ISSUE THREAD

**Issue by subins2000** [TheoIsDumb/charapara#1]
Would like to place it in footer of https://കിട്ടും.com/ as well :)

**Comment by theophinetheodore** [comment]
will start work today saar 😉 @subins2000

**Comment by theophinetheodore** [comment]
@subins2000 merged saar

this is the image in markdown syntax:
```![test](https://raw.githubusercontent.com/TheoIsDumb/charapara/master/static/kunnamkulam_optimized.svg)```

btw ill look into the prob you mentioned, im outdoors currently
